# Set the targets: all, clean
TARGETS = alpha beta
LIBS 	= lib
include ../common.mk

# Set the library targets for lib
LIB = lib
SOURCES = lib.c
include ../common_lib.mk

# Set the targets for prova1
TARGET = alpha
SOURCES = alpha.c
LIBS = lib
include ../common_target.mk

# Set the targets for prova2
TARGET = beta
SOURCES = beta.c
LIBS =
include ../common_target.mk
